[build]
  command = "npm run build"

[images]
  remote_images = ["https://github.com/.*"]

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[plugins]]
  package = "./netlify-plugin-cloudinary"

  [plugins.inputs]
  cloudName = "dzk3zrurn"
  