[build]
  functions = "netlify/functions" # Path to your functions folder

[[redirects]]
  from = "/api/selfsell"
  to = "/.netlify/functions/selfsell" 
  status = 200 

[[redirects]]
  from = "/api/traditional"
  to = "/.netlify/functions/traditional" 
  status = 200 

[[redirects]]
  from = "/api/companyInfo"
  to = "/.netlify/functions/company-info" 
  status = 200 